### ISSUE TITLE
Everyone try A1 Task1

### ISSUE THREAD

**Issue by rxxq** [rxxq/CSCC67-assignment-notes#2]
@crazyo @jaydoncct 

As discussed at the last meeting, everyone will try to do A1 Task1. 
Please push your changes to a branch with your name in it so we don't conflict with each other (e.g.: use `git push origin your_name/a1task1` instead of `git push origin master`)

**Comment by rxxq** [comment]
I've made a bit of progress on copying the strings in `argv` to the user address space, but I still need to reconstruct `argv`'s array of pointers in the userspace.

I think the issue with the padding comes up here because characters are 1 byte but pointers are 4 bytes. For example, assume that the address was a multiple of 4 at the beginning. You want to to add 3 chars and then a pointer. The 3 chars will take up only 3 bytes, so you need to pad by one byte before you can add the pointer.

**Comment by rxxq** [comment]
So the current version in the repo under the branch rex/a1task1 is an implementation with all the elements in place (copying strings, reconstructing array of char pointers for `argv`), but doesn't quite work yet. I still need to debug it and figure out the proper memory locations to set for the stack pointer so that the strings in `argv` will fit. Can you guys take a look at it? I might not have much time to work on this in the next few days

**Comment by jaydoncct** [comment]
OK!

2015-01-27 5:59 GMT+08:00 Xiuqi (Rex) Xia notifications@github.com:

**Comment by rxxq** [comment]
Ok, Just had an unexpected block of time due to one of my profs cancelling lecture. I debugged `runprogram` and fixed all the issues with it. Here is a summary of the issues.
- `gdb`'s `x` command by default displays 4 bytes at a time, but in sys161 one memory address points to only one byte. I confused myself for quite a while before I read [this](https://sourceware.org/gdb/onlinedocs/gdb/Memory.html) and found out that you can change how many bytes to display to match the way it's _actually_ set up in the hardware.
- There were various places where pointers/addresses got mixed up. The major one that was causing the problems was when I had an array in kernel memory storing addresses in user memory where the strings of `argv` have been copied, and I used `copyout` to copy the array into user memory. The problem was that copyout takes a pointer to kernel memory, not the values themselves, so I had to change it to use the `arrayname + i` notation instead of `arrayname[i]`.

Currently, `runprogram` is working (you can test it using `sys161 kernel 'p /testbin/argtest'` but the values of `argv` are hardcoded in `runprogram`. So the only thing left for task1 is to actually change the function definition of `runprogram` to take `argv` as an argument, and to make `cmd_prog_thread` in `menu.c` pass `argv` to `run program`. Anyway, this is a trivial change.

**Comment by rxxq** [comment]
Also, I forgot to mention that there is still a place in the `runprogram` where errors from `copyout` are not handled. We should remember to do that before submitting.
