### ISSUE TITLE
A1 Task 2

### ISSUE THREAD

**Issue by rxxq** [rxxq/CSCC67-assignment-notes#3]
@crazyo @jaydoncct 
Hey guys, I wrote up some notes on how to do A1T2 [in the wiki](../wiki/A1%3A-Task-2)

So before the weekend, let's try to understand what we need to do for each function. Like edit the code and add TODO comments indicating what we need to implement. I've assigned one function per person.
### Understand:
- [x] pid_join, pid_exit (@rxxq)
- [x] pid_detach (@crazyo)
- [x] thread_exit (@jaydoncct)
- [x] thread_fork
### Implement:
- [x] pid_join
- [x] pid_exit
- [x] pid_detach
- [x] thread_exit
- [x] thread_fork
### use pid_join and pid_detach
- [x] Use pid_join to make the menu thread wait until the child thread has finished. 
- [x] Add support for "&"; any command that is followed by a "&" should be detached, so that the menu thread does not wait for it.

**Comment by jaydoncct** [comment]
Noted with thanks.

Jaydon

2015-01-30 6:37 GMT+08:00 Xiuqi (Rex) Xia notifications@github.com:

**Comment by rxxq** [comment]
I've added some info on sleeping/waking [in the wiki](../wiki/A1%3A-Task-2)

My thoughts on how to do `pid_join` and `pid_exit`:

From the assignment instructions:

> When a joinable thread terminates, its `pidinfo` struct (containing the PID and exit status, along with other fields) must be retained until another thread performs `pid_join` (or `pid_detach`) on it.

So we need some way to keep track of threads waiting on an exiting thread, so we can know when we can delete the `pidinfo` struct of the exiting thread. I think we can do this by adding an integer `pid_nwaiting` to the `pid_info` struct that keeps track of how many threads are waiting for it. Every time a thread calls `pid_join` it increments `n_waiting` before going to sleep. When it wakes, it checks if the thread it was waiting on has exited. If so, it decrements `pid_nwaiting`. When a thread finds that it's about to decrement `pid_nwaiting` to zero, it can delete the `pid_info` of the exiting thread.

There is a special case when a thread exits before another thread calls `pid_join` on it. This means that we don't delete an exited thread with a `pid_nwaiting` of zero automatically. The first thread to call `pid_join` on it should notice that the `pid_nwaiting` is already zero and it will be the one to delete the exiting thread's `pid_info`.

**Comment by rxxq** [comment]
`pid_join` and `pid_detach` are done. I'm still working on various issues such as:
- [x] What happens to all the threads waiting on a thread, when a joined thread is detached?
- [x] In `thread_exit`, how do we know it's a user thread?
- [x] Implement the list of stuff in `pid_exit`'s docstring
- [ ] If have time, edit `waittest` to test situation where there are many threads waiting on the same thread

**Comment by rxxq** [comment]
Currently, if a thread is detached while there are other threads already waiting on it, the other threads will get woken up and they will return with EINVAL.

@crazyo suggests that maybe we should not allow detach to work in this case. I think this is also a reasonable way to do it. If we have time I might change the implementation to do that.
